# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ListeView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListeView(object):
    def setupUi(self, ListeView):
        ListeView.setObjectName("ListeView")
        ListeView.resize(478, 515)
        self.label_listedesetudiants = QtWidgets.QLabel(ListeView)
        self.label_listedesetudiants.setGeometry(QtCore.QRect(40, 20, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_listedesetudiants.setFont(font)
        self.label_listedesetudiants.setObjectName("label_listedesetudiants")
        self.listView_liste = QtWidgets.QListView(ListeView)
        self.listView_liste.setGeometry(QtCore.QRect(40, 50, 311, 351))
        self.listView_liste.setObjectName("listView_liste")
        self.pushButton_quitter = QtWidgets.QPushButton(ListeView)
        self.pushButton_quitter.setGeometry(QtCore.QRect(120, 420, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quitter.setFont(font)
        self.pushButton_quitter.setObjectName("pushButton_quitter")

        self.retranslateUi(ListeView)
        QtCore.QMetaObject.connectSlotsByName(ListeView)

    def retranslateUi(self, ListeView):
        _translate = QtCore.QCoreApplication.translate
        ListeView.setWindowTitle(_translate("ListeView", "Dialog"))
        self.label_listedesetudiants.setText(_translate("ListeView", "Liste des étudiants"))
        self.pushButton_quitter.setText(_translate("ListeView", "Quitter"))
